version: "3.8"

services:
  dev:
    build:
      context: ./sdk
      args:
        flutter_version: stable
    tty: true
    container_name: flutter-sdk
    working_dir: /application/src
    ports:
      - 5037:5037
      - 9005:9005
    volumes:
      - .:/application
    restart: unless-stopped
