version: "3.8"

services:
  dev:
    build:
      context: ./sdk
      args:
        flutter_version: stable
    tty: true
    container_name: flutter-sdk
    working_dir: /application/src
    ports:
      - ${ADB_PORT}:${ADB_PORT}
      - ${FIREBASE_LOGIN_AUTH_PORT}:${FIREBASE_LOGIN_AUTH_PORT}
    volumes:
      - .:/application
    restart: unless-stopped
