name: plant_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  google_sign_in: ^6.1.0
  go_router: ^6.5.6
  flutter_riverpod: ^2.3.4
  social_login_buttons: ^1.0.7
  flutter_localizations:
    sdk: flutter
  intl: 0.18.0
  cloud_firestore: ^4.5.2
  form_builder_validators: ^9.0.0
  firebase_storage: ^11.1.1
  flutter_image_compress: ^1.1.3
  flutter_form_builder: ^9.0.0
  flutter_hooks: ^0.18.6
  uuid: ^3.0.7
  hooks_riverpod: ^2.3.6
  image_picker: ^0.8.7+4
  path: ^1.8.2
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth_mocks: ^0.11.0
  package_info: ^2.0.2
  android_intent: ^2.0.2
  flutter_local_notifications: ^14.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19
  flutter_lints: ^2.0.0

flutter_icons:
  ios: false
  android: "ic_launcher"
  image_path: "assets/icons/logo.png"

flutter_native_splash:
  background_image: "assets/backgrounds/splash.png"
  background_image_dark: "assets/backgrounds/splash_dark.png"
  image: assets/icons/logo.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/logo.png
    - assets/images/plant_placeholder.png
    - assets/plant_types.json
